url: http://beamlabs.net/
baseurl: http://beamlabs.net/

# Site settings
title: Beam Labs
email: agiron123@gmail.com
description: "Official home page of Beam Labs."

# Team names, titles and social links
people:
- name: Andre Giron
  pic: andre
  position: Founder
  social:
    - title: github
      url: http://github.com/agiron123
    - title: twitter
      url: https://twitter.com/agiron_78
    - title: linkedin
      url: https://www.linkedin.com/in/andre-giron-bb921943
    - title: file-o # Resume information
      url: http://andregiron.me/assets/Docs/ANDRE_GIRON_RESUME.pdf
  specialization: I create websites using the latest technologies, and specialize in JavaScript and NodeJS development, using web frameworks like React, Angular, and Express. Iâ€™ve worked on a wide range of solo and collaborative projects, and am eager to come up with a customized solution to your development needs. For more information, visit my personal website. (http://andregiron.me)

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/BeamLabs

# Postal address (add as many lines as necessary)
address:
  - line: Atlanta

# Build settings
markdown: kramdown
permalink: pretty
port: 4001
